/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CVRxEarth (https://sketchfab.com/CVRxEarth)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-spot-from-across-the-spider-verse-f07168481ba047969512fa9c075d1181
Title: The Spot from Across The Spider Verse
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HackerRoom5(props) {
    const { nodes, materials } = useGLTF('./models/hacker-room5.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.844}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <group position={[400, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <primitive object={nodes._rootJoint} />
                        <skinnedMesh
                            geometry={nodes.Object_1059.geometry}
                            material={materials.The_Spot_Main_Material}
                            skeleton={nodes.Object_1059.skeleton}
                        />
                    </group>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane001_Spot_Hole_0.geometry}
                        material={materials.Spot_Hole}
                        position={[-24.644, 32.703, -75.498]}
                        rotation={[-0.831, -0.223, -0.028]}
                        scale={13.433}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002_Spot_Hole_0.geometry}
                        material={materials.Spot_Hole}
                        position={[1.231, 67.462, 17.255]}
                        rotation={[-1.281, 0.208, 0.009]}
                        scale={[48.356, 35.487, 35.487]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane003_Spot_Hole_0.geometry}
                        material={materials.Spot_Hole}
                        position={[23.355, 41.631, 52.467]}
                        rotation={[-1.329, 0.051, 0.066]}
                        scale={16.952}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane004_Spot_Hole_0.geometry}
                        material={materials.Spot_Hole}
                        position={[39.216, 115.017, 48.57]}
                        rotation={[-1.065, -0.293, 0.012]}
                        scale={14.356}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane005_Spot_Hole_0.geometry}
                        material={materials.Spot_Hole}
                        position={[-32.155, 110.904, 40.638]}
                        rotation={[-1.184, 0.625, -0.507]}
                        scale={14.356}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane006_Spot_Hole_0.geometry}
                        material={materials.Spot_Hole}
                        position={[-27.191, 133.403, 309.439]}
                        rotation={[0.229, 0.358, -2.089]}
                        scale={14.356}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane007_Spot_Hole_0.geometry}
                        material={materials.Spot_Hole}
                        position={[68.375, 105.404, 329.778]}
                        rotation={[0.354, -0.345, -1.845]}
                        scale={14.356}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane008_Spot_Hole_0.geometry}
                        material={materials.Spot_Hole}
                        position={[62.595, 146.993, -45.025]}
                        rotation={[0.154, -0.266, -0.292]}
                        scale={7.767}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane009_Spot_Hole_0.geometry}
                        material={materials.Spot_Hole}
                        position={[-89.064, 108.116, -78.892]}
                        rotation={[0.362, 0.575, -0.258]}
                        scale={12.521}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane011_Spot_Hole_0.geometry}
                        material={materials.Spot_Hole}
                        position={[80.171, 146.933, 186.739]}
                        rotation={[0.066, -0.234, 0.481]}
                        scale={18.453}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.BezierCurve_Spot_Trails_0.geometry}
                        material={materials.Spot_Trails}
                        position={[44.031, 169.176, 70.2]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.BezierCurve001_Spot_Trails_0.geometry}
                        material={materials.Spot_Trails}
                        position={[-40.349, 132.424, 47.778]}
                        rotation={[-0.73, -0.205, 1.348]}
                        scale={30.888}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.BezierCurve002_Spot_Trails_0.geometry}
                        material={materials.Spot_Trails}
                        position={[-90.291, 111.2, -66.463]}
                        rotation={[-0.653, 0.09, 1.13]}
                        scale={100}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.The_Spot_The_Spot_Main_Material_0.geometry}
                        material={materials.The_Spot_Main_Material}
                        rotation={[0, 0.047, 0]}
                        scale={107.849}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.The_Spot002_The_Spot_Main_Material_0.geometry}
                        material={materials.The_Spot_Main_Material}
                        position={[-5.797, 0, -63.665]}
                        rotation={[0, -0.374, 0]}
                        scale={107.849}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.The_Spot004_The_Spot_Main_Material_0.geometry}
                        material={materials.The_Spot_Main_Material}
                        position={[54.026, 102.484, 360.199]}
                        rotation={[-2.281, -0.638, -1.446]}
                        scale={107.849}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.The_Spot005_The_Spot_Main_Material_0.geometry}
                        material={materials.The_Spot_Main_Material}
                        position={[-17.638, 131.156, 336.93]}
                        rotation={[-2.843, 1.113, 2.244]}
                        scale={107.849}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('./models/hacker-room5.glb')

